version: "3.0"

services:
  tpp:
    build:
      context: .
      dockerfile: tpp/Dockerfile
  financroo:
    build:
      context: .
      dockerfile: financroo/Dockerfile
  bank:
    build:
      context: .
      dockerfile: bank/Dockerfile
